spring.application.name=eRegistrar

spring.datasource.url=jdbc:postgresql://localhost:5432/eregistrar_db
spring.datasource.username=tegshe
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080